### ISSUE TITLE
Wave source hierarchy browser

### ISSUE THREAD

**Issue by bluecmd** [ngscopeclient/scopehal-apps#216]
In order to support sources with a lot of channels, it is inevitable that glscopeclient will have to offer some sort of interface to select and add a lot of channels at once. Right now this is done by the "Add" menu, which works pretty well for a few channels commonly used on analog scopes.

The most extreme examples I can think of are SPICE simulations which can easily have thousands of nets in the results, 
I made an example SPICE waveform here: [lots-of-inverters.tar.zst](http://storage.googleapis.com/bluecmd/lots-of-inverters.tar.zst). It contains a 300MB SPICE simulation of some hundred inverters in a 2-level hierarchy.

Some inspiration from GTKwave here:
![image](https://user-images.githubusercontent.com/149442/95196687-b4a56280-07d8-11eb-9fc6-e59df22581d6.png)

Other simulation tools usually have something similar, a type of "filesystem" folder/trace structure that allows navigation. Some viewers have a flat hierarchy but allowing you to filter.

For VCD and FST the folder-hierarchy maps really well as they are hierarchical anyway. For SPICE data they are more implicit, like this:

```
v(x16.net30)    voltage
v(x16.net31)    voltage
v(net16)        voltage
v(sky130_fd_pr__esd_nfet_05v0_nvt.pm3)  voltage
v(m.x16.xm60.msky130_fd_pr__nfet_01v8#dbody)    voltage
v(m.x16.xm60.msky130_fd_pr__nfet_01v8#body)     voltage
i(v.x3.vsense-vcc)      current
i(v.x2.vsense-in)       current
i(v.x2.vsense-vcc)      current
i(v.x1.vsense-in)       current
i(v.x1.vsense-vcc)      current
i(v1.8) current
i(v.100mhz)     current
```

**Comment by bluecmd** [comment]
For reference, this is what gaw does for SPICE right now:
![image](https://user-images.githubusercontent.com/149442/95197487-f71b6f00-07d9-11eb-9204-a690457c652b.png)

That's a long list of unfilterable SPICE data names. As a user that is pretty annoying and not so friendly, so let's avoid that :-)

**Comment by bluecmd** [comment]
After speaking with @azonenberg I will post some commercial examples as well.

Here is Cadence's Visualization tool showing a quite busy setup with SPICE data:
![image](https://user-images.githubusercontent.com/149442/95241126-a3c31400-080d-11eb-8e0a-cb66604485a2.png)
![image](https://user-images.githubusercontent.com/149442/95241434-06b4ab00-080e-11eb-8970-b0618922d7bb.png)

Here is Synopsys WaveView:
![image](https://user-images.githubusercontent.com/149442/95241223-c0f7e280-080d-11eb-9e62-d0472fa0f686.png)
![image](https://user-images.githubusercontent.com/149442/95241252-c81ef080-080d-11eb-95b3-216c1e0bb1fb.png)

**Comment by azonenberg** [comment]
Anybody have a screenshot of VCS for reference? The only ones I have are full of customer data and I can't share.

**Comment by bluecmd** [comment]
Maybe these are from VCS? https://github.com/pulp-platform/fpnew/issues/24#issuecomment-613736398
