### ISSUE TITLE
Improve state of developer documentation

### ISSUE THREAD

**Issue by azonenberg** [ngscopeclient/scopehal-apps#28]

**Comment by bvernoux** [comment]
1) Add explicitly -DCMAKE_BUILD_TYPE=Release for Release and -DCMAKE_BUILD_TYPE=Debug for Debug build in both doc and Readme.md 
2) Add cp -r ../src/glscopeclient/masks 
3) Add some hints to debug under windows

How to Debug Rigol MSO5000 Ethernet
Debug workaround with gdb on Windows with MSYS2 mingw64:
```
cd ~
cd glscopeclient_build
export OMP_WAIT_POLICY=PASSIVE
winpty gdb ./glscopeclient.exe
set args --debug RigolMSO5k:rigol:lan:xx.xx.xx.xx:5555
run
```

**Comment by azonenberg** [comment]
Closing now that we have basic Doxygen support, we can file separate tickets for specific holes in the docs in the future
