### ISSUE TITLE
macOS: Scale GUI for Retina displays

### ISSUE THREAD

**Issue by rgov** [ngscopeclient/scopehal-apps#625]
The GUI is awkwardly scaled on macOS, where most Apple displays are going to be high DPI ("Retina"). Compare the menu text with the titlebar which is the normal system font size. The toolbar items look the right size.

<img width="1018" alt="image" src="https://github.com/ngscopeclient/scopehal-apps/assets/108767/c8858d67-d973-4cc1-aac0-5aa68117f845">

There's some discussion here: https://github.com/ocornut/imgui/issues/3757

**Comment by rgov** [comment]
`GDK_SCALE=2` doesn't do it (#255 etc.)

**Comment by azonenberg** [comment]
ngscopeclient doesn't use GTK, so any of the pre-2022 issues about scaling won't be relevant.

Font scaling is calculated based on GetContentScale() from imgui (see MainWindow::UpdateFonts()).

Is it possible there's a double scaling going on where the OS is trying to scale fonts and the application also is, and they're stepping on each other?

+ @lainy @602p

**Comment by azonenberg** [comment]
Most UI elements are calculated with sizes based on the font size, so as text size scales everything else should scale to match.

So the root cause is likely the font scaling factor being off somehow.

**Comment by rgov** [comment]
Looks great, thanks @d235j!

<img width="1060" alt="image" src="https://github.com/ngscopeclient/scopehal-apps/assets/108767/8faac477-7ed7-4eea-ba24-7c90f1aec709">
