### ISSUE TITLE
ngscopeclient: Add another draggable trigger level cursor for two-level triggers

### ISSUE THREAD

**Issue by hansemro** [ngscopeclient/scopehal-apps#658]
Two-level triggers (such as RuntTrigger, SlewRateTrigger, and WindowTrigger) will benefit from having a pair of draggable cursors for upper and lower trigger levels.

Currently, WaveformArea will give/spam the following warning when using any TwoLevelTrigger:
```
Warning: Two-level triggers not implemented
```

**Comment by azonenberg** [comment]
Ah yes, that was a feature from glscopeclient that I guess we never ported over to ng. Shouldn't take long to do.
