### ISSUE TITLE
macOS: Font size cannot be set to 13pt or 15pt

### ISSUE THREAD

**Issue by rgov** [ngscopeclient/scopehal-apps#690]
I'm on a Retina display on a MacBook Pro.

Setting the font to 13pt or 15pt causes nothing to change in the GUI. For example: 12pt -> 13pt does nothing. 13pt -> 14pt increases the size. 14pt -> 13pt does nothing. 13pt -> 12pt decreases the size.

**Comment by azonenberg** [comment]
This feels like a scaling factor of around 2.0 being applied (maybe in imgui, maybe our code) in the integer domain and losing the fractional part of the font size.

+ @d235j
