### ISSUE TITLE
New Windows build steps:

### ISSUE THREAD

**Issue by AEW2015** [ngscopeclient/scopehal-apps#715]
I need to run this to build on windows:
* pacman -S mingw-w64-ucrt-x86\_64-make
* cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
* mingw32-make -j4

**Comment by AEW2015** [comment]
Ok you can use the ninja files, just instead of `make` do this
`cmake --build . -j4` or `ninja -j4`

**Comment by azonenberg** [comment]
Fixed in current docs
