### ISSUE TITLE
Sidebar "triggered" / "armed" badges can flicker very rapidly with some WFM/s speeds

### ISSUE THREAD

**Issue by azonenberg** [ngscopeclient/scopehal-apps#775]
With scopes triggering at about 8 WFM/s there's an extremely distracting ~4 Hz flickering in the sidebar.

Proposal: pulse-stretch triggers faster than about 1 Hz to "running" or similar

**Comment by jwise** [comment]
I recommend using the same "slow" / "fast" hysteresis mechanism as for channels.

**Comment by azonenberg** [comment]
Fixed by #788
